name: render_notion_pages
on: workflow_dispatch
# https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
permissions: write-all

jobs:
  render_notion_pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: browser-actions/setup-chrome@v1 # only for html2pdf conversion

      - uses: actions/checkout@v4

      - name: Clone notionexportstatic
        run: git clone https://github.com/vadimkantorov/notionexportstatic
      
      - name: Generate single HTML and PDF and Markdown and optionally save the content into everything.json
        run: |
          mkdir -p ./html/ ./markdown/

          # optionally refresh ./everything.json
          [ $DOWNLOAD_FROM_NOTION ] && python ./notionexportstatic/notionexportstatic.py --notion-token $NOTION_TOKEN --notion-page-id $NOTION_PAGE_ID -o ./everything.json --extract-mode single.json
          
          # generate single Markdown from a pre-downloaded ./everything.json
          python ./notionexportstatic/notionexportstatic.py -i everything.json -o ./markdown/single.md --config-json _config.json --extract-mode single.md
          # generate single HTML and PDF from a pre-downloaded ./everything.json
          python ./notionexportstatic/notionexportstatic.py -i everything.json -o ./html/single.html --config-json _config.json --extract-mode single.html
          # html2pdf conversion
          chrome --headless --print-to-pdf=./single.pdf ./html/single.html

        env:
          DOWNLOAD_FROM_NOTION: 1
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          
      - name: Generate flat HTML and Markdown from a pre-downloaded JSON
        run: |
          mkdir -p ./html/ ./markdown/
          # generate flat HTML from a pre-downloaded ./everything.json
          python ./notionexportstatic/notionexportstatic.py -i everything.json -o ./html/ --config-json _config.json --extract-mode flat.html
          # generate flat Markdown from a pre-downloaded ./everything.json
          python ./notionexportstatic/notionexportstatic.py -i everything.json -o ./markdown/ --config-json _config.json --extract-mode flat.md  --extract-assets  --sitemap-xml ./markdown/sitemap.xml --base-url https://vadimkantorov.github.io/notionexportstatic/markdown/ --base-url-removesuffix=.md

      - name: Push HTML and Markdown
        run: |
          git config user.name 'Vadim Kantorov'
          git config user.email 'vadimkantorov@gmail.com'
          git add -f -A ./everything.json ./html/ ./markdown/
          git commit -a -m ...
          git push

      - name: Single PDF file
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: single.pdf
