name: render_notion_pages
# https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
permissions: write-all

on:
  workflow_dispatch:
    inputs:
      commaseparatednotionpageids:
        description: 'comma separated notion page ids'
        required: false
        default: '183af621072445438c48af7dd4f21f5c'
      downloadfromnotion:
        description: 'download from notion or use a pre-downloadeded and pre-committed ./everything.json'
        type: boolean
        required: false

jobs:
  render_notion_pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Prerequisites
        run: python -m pip install notion-client --user

      - uses: browser-actions/setup-chrome@v1 # only for html2pdf conversion

      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Clone notionexportstatic
        run: git clone --branch master https://github.com/vadimkantorov/notionexportstatic
      
      - name: Optionally refresh ./everything.json
        if: github.event.inputs.downloadfromnotion == 'true'
        run: python ./notionexportstatic/notionexportstatic.py --notion-token $NOTION_TOKEN --notion-page-id $NOTION_PAGE_ID -o ./everything.json --extract-mode single.json
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ github.event.inputs.commaseparatednotionpageids }}
      
      - name: Generate single HTML and PDF and Markdown
        run: |
          mkdir -p ./html/ ./markdown/
          # generate single Markdown from a pre-downloaded ./everything.json
          python ./notionexportstatic/notionexportstatic.py -i everything.json -o ./markdown/single.md --config-json _config.json --extract-mode single.md
          # generate single HTML and PDF from a pre-downloaded ./everything.json
          python ./notionexportstatic/notionexportstatic.py -i everything.json -o ./html/single.html --config-json _config.json --extract-mode single.html
          # html2pdf conversion
          chrome --headless --print-to-pdf=./everything.pdf ./html/single.html
          
      - name: Generate flat HTML and Markdown from a pre-downloaded JSON
        run: |
          mkdir -p ./html/ ./markdown/
          # generate flat HTML from a pre-downloaded ./everything.json
          python ./notionexportstatic/notionexportstatic.py -i everything.json -o ./html/ --config-json _config.json --extract-mode flat.html
          # generate flat Markdown from a pre-downloaded ./everything.json
          python ./notionexportstatic/notionexportstatic.py -i everything.json -o ./markdown/ --config-json _config.json --extract-mode flat.md  --extract-assets  --sitemap-xml ./markdown/sitemap.xml --base-url https://vadimkantorov.github.io/notionexportstatic/markdown/ --base-url-removesuffix=.md

      - name: Push HTML and Markdown
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -f -A ./everything.json ./everything.pdf ./html/ ./markdown/
          git commit -a -m ...
          git push
